Add string.Interpolate
Facepunch/garrysmod pull request #1480
Opened 2018-04-22 09:44 UTC by sannysc

This is a useful function for having readable format strings as opposed to the normal ones.

Example usage:

```lua
print(string.Interpolate("Hello {name}!", {name = "garry"}))
```
That code would output ```Hello garry!```

It only replaces valid lua identifiers between braces. I figured there isn't really a need to have it work with anything else, considering one of this function's advantages is that it lets you read the format string to more easily understand the intent of the message.

2022-08-02 14:46 UTC, robotboy655 reviewed
Why not just use `string.format`?

2022-08-02 14:59 UTC, Kefta commented
Named parameters instead of ordered is useful for translated strings where the order of parameters can change based on the language.

2022-08-02 15:36 UTC, robotboy655 commented
Fair enough. Not sure how I feel about the error/assert, surely it would be better to just have the token not replaced?

2022-08-02 16:08 UTC, Kefta commented
I agree.

2022-08-02 16:34 UTC, robotboy655 requested changes

2022-08-02 16:34 UTC, robotboy655 commented on garrysmod/lua/includes/extensions/string.lua
> +		assert( value != nil, "string.Interpolate: lookup failed for '" .. key .. "'" )
This should not error, but should simply not replace the token.

2023-01-17 13:57 UTC, robotboy655 approved these changes

2023-01-17 13:58 UTC, merged