Update cl_init.lua
Facepunch/garrysmod pull request #1770
Opened 2021-02-16 16:41 UTC by BullyHunter32

- Removed if statement and replaced it with 'and' and 'or'
- Entered 'view' table indexes directly upon creation (line 351)

2021-02-16 17:06 UTC, robotboy655 commented
These changes serve no purpose.

2021-02-16 17:44 UTC, robotboy655 requested changes

2021-02-16 17:44 UTC, robotboy655 commented on garrysmod/gamemodes/base/gamemode/cl_init.lua
> +	local team = ent.Team and ent:Team() or TEAM_UNASSIGNED
This is a pointless change and should be reverted, then I can merge it.

2021-02-17 08:34 UTC, GitSparTV approved these changes

2021-02-17 14:21 UTC, robotboy655 approved these changes

2021-02-17 14:21 UTC, merged