Send the entity to send fewer bits than sending the class
Facepunch/garrysmod pull request #1984
Opened 2023-06-26 23:46 UTC by MoskalykA

Hi
I suggest sending an entity to send fewer bits than sending the class, which is the same as sending a string.
An entity corresponds to 13 bits whereas a string with two characters corresponds to a higher number of bits and we know that the class of an entity is not two characters long.

2023-06-26 23:59 UTC, robotboy655 commented
Have you actually tested this change on an actual server?

2023-06-27 00:13 UTC, Kefta commented
I believe net messages will always reach the client before its knowledge of entity deletion when dispatched at the same time, but this should be tested extensively. I'll do some this weekend.

2023-06-27 00:15 UTC, Kefta requested changes

2023-06-27 00:15 UTC, Kefta commented on garrysmod/gamemodes/base/gamemode/npc.lua
> +local worldspawn = Entity(0)
Just call game.GetWorld() at the time the hook is ran - this optimisation is not needed. Also the variable names should be changed to reflect the fact that they're an entity now, not a class string.

2023-06-27 00:30 UTC, MoskalykA commented
> Have you actually tested this change on an actual server? The reason for sending the classname is that the entity may be deleted by the time the message gets to the client.

I've actually tested my modifications but I hadn't thought of that, I'll test it tomorrow.

2023-06-27 00:31 UTC, MoskalykA commented
> I believe net messages will always reach the client before its knowledge of entity deletion when dispatched at the same time, but this should be tested extensively. I'll do some this weekend.

Interesting, I'll let you check it out for yourself.

2023-06-27 16:20 UTC, FlorianLeChat commented
Have you tested this in an environment where a server is under heavy network load due to a large number of players and network requests can take a **longer** time to be broadcasted to players? Your suggestion seems to be pretty weak in such cases where bad timing is enough to cause an error.

2023-06-27 17:07 UTC, MoskalykA commented
> Have you tested this in an environment where a server is under heavy network load due to a large number of players and network requests can take a **longer** time to be broadcasted to players? Your suggestion seems to be pretty weak in such cases where bad timing is enough to cause an error.

I've just tried to get as many requests as possible and it's still working, but I have no way of testing this with a server full of players and sending more requests than I've been able to get.

2023-07-02 23:55 UTC, MoskalykA commented
Hi, I added the modification to a friend's server, you were right

2023-07-02 23:55 UTC, closed without merging