Updates/Option to inherit bodygroups from player->hands in player_manager
Facepunch/garrysmod pull request #1992
Opened 2023-07-11 15:08 UTC by Phoenixf129-2

- Adds player_manager.AllHandNames accessor for local hand names table
- Adds player_manager.GetBodyGroupsAsStr ( as GetBodyGroups returns a table and we need a string! ) 
- Adds matchBodyGroups support to player_manager.AddValidHands - just like matchBodySkin (default false)
- Updates GM:PlayerSetHandsModel for gamemodes base/terrortown to include inheriting bodygroups

2023-07-11 15:21 UTC, Phoenixf129-2 commented
should have been on it's own patch/branch, oh well, next time

2023-08-03 17:27 UTC, robotboy655 requested changes

2023-08-03 17:27 UTC, robotboy655 commented on garrysmod/lua/includes/modules/player_manager.lua
> +function GetBodyGroupsAsStr( ply )
I think this should be moved to `lua/includes/extensions/entity.lua` as an entity extension, to complement https://wiki.facepunch.com/gmod/Entity:SetBodyGroups

The code should also conform to https://github.com/Facepunch/garrysmod/blob/master/CONTRIBUTING.md aka be consistent with the rest of the code base.

Also, should be named `Entity:GetBodyGroupsAsString`, `Entity:GetBodyGroupString` or `Entity:GetActiveBodyGroups`

2023-08-03 17:27 UTC, robotboy655 commented on garrysmod/lua/includes/modules/player_manager.lua
> +function AllHandNames( )
Perhaps `AllViewModelHands()`? Or `AllValidVMHands()`?

2023-08-03 17:27 UTC, robotboy655 commented on garrysmod/gamemodes/terrortown/gamemode/player.lua
> +      ent:SetBodyGroups( info.matchBodyGroups and player_manager.GetBodyGroupsAsStr( pl ) or info.body )
This code should be style-consistent with the rest of TTT code.

2024-10-02 15:11 UTC, closed without merging