Fix error when using sent_ball on non-singleplayer server
Facepunch/garrysmod pull request #2016
Opened 2023-10-08 12:21 UTC by callumok2004

Fixes `Trying to remove server entity sent_ball#335 on client!`

2023-10-08 19:17 UTC, Kefta requested changes

2023-10-08 19:17 UTC, Kefta commented on garrysmod/lua/entities/sent_ball.lua
> +	if ( activator:IsPlayer() ) and ( ( game.SinglePlayer() and CLIENT ) or SERVER ) then
Just change this check to SERVER, entities should never be removed on the client.

2023-10-08 23:25 UTC, Kefta commented
Add the parentheses back around the if-condition and this is good to go.

2023-10-09 10:09 UTC, robotboy655 commented
I cannot reproduce such an issue.

https://wiki.facepunch.com/gmod/ENTITY:Use
`ENTITY:Use` is not even called on the client by the base game as far as I am aware.

2023-10-13 12:10 UTC, robotboy655 commented
Closing, as this tries to fix a non-existent issue as far as I can tell, and I see no replies to my comment above.

2023-10-13 12:10 UTC, closed without merging