Make it easier to click on addons in the Addons list
Facepunch/garrysmod pull request #2018
Opened 2023-10-12 07:56 UTC by brandonsturgeon

### Summary
While managing lots of addons, it's really nice to have the checkbox for bulk actions.

However, it's also kind of cumbersome to _snipe_ the checkbox on each Addon when you're trying to select a lot of them at once.

This PR lets players click anywhere within the Addon panel to select/deselect the Addon.

### Demo
https://github.com/Facepunch/garrysmod/assets/7936439/987161e8-66ca-494f-95a6-1680ea74563c

### Details

The PR is actually really simple. A new click handler is added to the `worskhopicon` element that will Toggle the Selected state of the Addon.

However, because there are child click actions within the same menu, we have to update all of them to stop the click event before it triggers the new one _(events bubble up to their parents until something stops them)_.
This means that we had to pass the `event` through to all of the functions that respond to `on-click` actions in this panel.

One caveat to this would be the checkbox itself. Because it binds directly to the value, we also had to give it an `on-click` handler that stops the click event from propagating.

I also made sure it would work fine if the `event` wasn't present (i.e. if the function was called from anywhere but the menu) 👍 

https://github.com/Facepunch/garrysmod/assets/7936439/8c10ca9d-28d5-4c12-b4b0-14cb4500b9cc

2023-10-31 12:45 UTC, robotboy655 requested changes
Actually, this works even better:

```lua
	$scope.ToggleSelect = function( file, event )
	{
		var en = event.target.nodeName.toLowerCase();
		if ( en != "controls" && en != "description" && en != "workshopicon" ) return;

		$scope.SelectedItems[file.id] = !$scope.SelectedItems[file.id];
		if ( event ) event.stopPropagation();
	}
```

2023-10-31 19:49 UTC, brandonsturgeon commented
> I like the idea (despite the showcase)

Sorry, it was all I was subscribed to at the time.


> Actually, this works even better:
> 
> ```js
> 	$scope.ToggleSelect = function( file, event )
> 	{
> 		var en = event.target.nodeName.toLowerCase();
> 		if ( en != "controls" && en != "description" && en != "workshopicon" ) return;
> 
> 		$scope.SelectedItems[file.id] = !$scope.SelectedItems[file.id];
> 		if ( event ) event.stopPropagation();
> 	}
> ```

I'll give this a try 👍

2023-11-01 20:18 UTC, brandonsturgeon commented
That was a great suggestion - works great!

Thank you - those changes were applied.

2023-11-02 10:30 UTC, robotboy655 approved these changes

2023-11-02 12:18 UTC, robotboy655 requested changes

2023-11-02 12:18 UTC, robotboy655 commented on garrysmod/html/template/addon_list.html
> +				<description ng-click="ToggleSelect( file, $event )">{{GetAddonDescription( file )}}</description>
ng-click can be applied to `workshopicon` with the changes to `ToggleSelect`

2023-11-02 13:29 UTC, robotboy655 approved these changes

2023-11-02 13:29 UTC, merged