Added Turkish Language
Facepunch/garrysmod pull request #2028
Opened 2023-11-18 11:48 UTC by NovaDiablox

This time done from scratch, can use it comfortably.

2023-11-22 10:37 UTC, NovaDiablox commented on garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
> +
Missing " at the end of the sentence.

2023-11-22 13:20 UTC, NovaDiablox commented on garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
> +
There needs to be a " char after the dot.

2023-11-22 13:22 UTC, NovaDiablox commented on garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
> +
Ok I fixed it.

2023-11-25 20:08 UTC, svdm requested changes

2023-11-25 20:08 UTC, svdm commented on garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
> +L.karma_dmg_other = "Karman {amount}. |||UNTRANSLATED_CONTENT_START|||As a result all damage you deal is reduced by {num}%"|||UNTRANSLATED_CONTENT_END|||
Still problem here

2023-11-25 21:17 UTC, NovaDiablox commented on garrysmod/gamemodes/terrortown/gamemode/lang/turkish.lua
> +L.karma_dmg_other = "Karman {amount}. |||UNTRANSLATED_CONTENT_START|||As a result all damage you deal is reduced by {num}%"|||UNTRANSLATED_CONTENT_END|||
Done

2023-11-26 11:59 UTC, merged