Prevent infinite loop from `panel:SetDragParent`
Facepunch/garrysmod pull request #2058
Opened 2024-02-26 21:54 UTC by Timmy-the-nobody

2024-02-27 18:56 UTC, robotboy655 commented
I think it's best to add a check in `meta:DragMousePress( mcode )` instead, in case some megamind directly sets the internal variable `m_pDragParent`.

https://github.com/Facepunch/garrysmod/blob/0d8135682e7353d75688c71f57a3cb170d2f3a40/garrysmod/lua/includes/extensions/client/panel/dragdrop.lua#L418

2024-02-27 18:56 UTC, robotboy655 requested changes
I think it's best to add a check in `meta:DragMousePress( mcode )` instead, in case some megamind directly sets the internal variable `m_pDragParent`.

https://github.com/Facepunch/garrysmod/blob/0d8135682e7353d75688c71f57a3cb170d2f3a40/garrysmod/lua/includes/extensions/client/panel/dragdrop.lua#L418

2024-02-28 01:55 UTC, Timmy-the-nobody commented
That's right, I just made the change

2024-02-28 02:14 UTC, robotboy655 commented
I was thinking more in the way of 
```
if ( IsValid( self.m_pDragParent ) && self.m_pDragParent != self ) then
```

Which would make most sense and not prevent code below the IF block from running.

2024-02-28 13:08 UTC, Timmy-the-nobody commented
> I was thinking more in the way of
> 
> ```
> if ( IsValid( self.m_pDragParent ) && self.m_pDragParent != self ) then
> ```
> 
> Which would make most sense and not prevent code below the IF block from running.

Done 🙌

2024-02-28 13:43 UTC, merged