Allow custom error message for CanArmDupe
Facepunch/garrysmod pull request #2065
Opened 2024-03-02 07:46 UTC by brandonsturgeon

Adds a second return for the `CanArmDupe` hook that, when provided _(and the first parameter is `false`)_, will override the default failure message.

2024-07-09 16:49 UTC, robotboy655 requested changes
This new behavior should also be mimicked in `arming.lua`.

2024-07-09 17:07 UTC, brandonsturgeon commented
Thanks! Done ✔️

2024-07-10 11:50 UTC, robotboy655 requested changes
You still missed one instance of the hook call here:
https://github.com/Facepunch/garrysmod/blob/a3453cb1e3e9090d8c77b8c739ae5c54766158f4/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/arming.lua#L66-L67

2024-07-10 16:10 UTC, brandonsturgeon commented
Oops! I added it there too ✔️

2024-07-10 17:07 UTC, merged