Optimize string.GetFileFromFilename
Facepunch/garrysmod pull request #2093
Opened 2024-07-04 05:35 UTC by afxnatic

no longer uses a loop and has far fewer C calls as a result

2024-07-09 12:18 UTC, robotboy655 requested changes
Your implementation with the following input does not produce desired output:
```
print( "OLD", string.GetFileFromFilename( "garrysmod/lua/modules\\string.lua" ) )
print( "NEW", string.GetFileFromFilename2( "garrysmod/lua/modules\\string.lua" ) )

OLD	string.lua
NEW	modules\string.lua
```

2024-07-09 12:18 UTC, robotboy655 commented on garrysmod/lua/includes/extensions/string.lua
> +	-- Way faster than fetching length and calling two C functions per character.
"meta" comments like this should not be included in code.

2024-07-09 12:18 UTC, robotboy655 commented on garrysmod/lua/includes/extensions/string.lua
> +	local slashPosition, _, _ = string.find( reversePath, "/", 1 ) or string.find( reversePath, "\\", 1 )
Adding `true` for the 3rd param should make this even faster.

2024-07-10 22:00 UTC, afxnatic commented
> Your implementation with the following input does not produce desired output:
> 
> ```
> print( "OLD", string.GetFileFromFilename( "garrysmod/lua/modules\\string.lua" ) )
> print( "NEW", string.GetFileFromFilename2( "garrysmod/lua/modules\\string.lua" ) )
> 
> OLD	string.lua
> NEW	modules\string.lua
> ```

test with 222193e8d288b14a70b808061161e1308ddf7f95 and this issue should no longer be present

2024-07-11 10:54 UTC, robotboy655 commented
You cannot just flip the string,find's and expect it to work:
```
print( "OLD", string.GetFileFromFilename( "garrysmod/lua\\modules/string.lua" ) )
print( "OLD", string.GetFileFromFilename( "garrysmod/lua/modules\\string.lua" ) )

print( "NEW", string.GetFileFromFilename2( "garrysmod/lua\\modules/string.lua" ) )
print( "NEW", string.GetFileFromFilename2( "garrysmod/lua/modules\\string.lua" ) )
```

```
OLD	string.lua
OLD	string.lua
NEW	modules/string.lua
NEW	string.lua
```

2024-07-12 19:03 UTC, afxnatic commented
> You cannot just flip the string,find's and expect it to work:

string.find is actually flawed for any path that mixes backslashes and forward slashes, my bad for not realizing that

i replaced the existing string.find solution with a lua pattern in 886ed13251a46be2b026c55531dc2eed6ff07db1
```
print( "OLD", string.GetFileFromFilename( "garrysmod/lua/modules/string.lua" ) )
print( "OLD", string.GetFileFromFilename( "garrysmod/lua\\modules/string.lua" ) )
print( "OLD", string.GetFileFromFilename( "garrysmod/lua/modules\\string.lua" ) )

print( "NEW", string.GetFileFromFilename2( "garrysmod/lua/modules/string.lua" ) )
print( "NEW", string.GetFileFromFilename2( "garrysmod/lua\\modules/string.lua" ) )
print( "NEW", string.GetFileFromFilename2( "garrysmod/lua/modules\\string.lua" ) )
```

```
OLD	string.lua
OLD	string.lua
OLD	string.lua
NEW	string.lua
NEW	string.lua
NEW	string.lua
```

it even keeps this issue:
```
print( "OLD", string.GetFileFromFilename( "garrysmod/lua/modules" ) )
print( "NEW", string.GetFileFromFilename2( "garrysmod/lua/modules" ) )
```

```
OLD	modules
NEW	modules
```

if its still buggy or doesn't match original behavior, just close this PR

2024-07-15 14:30 UTC, robotboy655 commented
Using Lua patterns is significantly slower than the current code. It's why these functions were changed to not use them in the first place. (https://github.com/Facepunch/garrysmod/commit/7017e076718a953aa9bfdc9ee4f3b490d6852cea)

![image](https://github.com/user-attachments/assets/a7086e37-ebd2-473c-8087-141660043e69)
Your current proposal also has a regression when the string has no slashes.

Using 2 string.find calls can be faster in some cases, but also slower in others.

2024-07-15 14:30 UTC, closed without merging