Improvement Sandbox ENT`s
Facepunch/garrysmod pull request #2109
Opened 2024-08-30 20:50 UTC by friztailo

Improvements:
- The result of ENT:BeingLookedAtByLocalPlayer() is now cached in the current frame to prevent unnecessary re-tracing.
- Lights, lamps, emitters, thrusters have been optimized in terms of creating unnecessary garbage. 
  Now they will not drop your fps so often due to garbage collection.

2024-09-03 12:28 UTC, robotboy655 requested changes

2024-09-03 12:28 UTC, robotboy655 commented on garrysmod/gamemodes/sandbox/entities/entities/gmod_thruster.lua
> +list.Set( "ThrusterEffects", "none", { print = "#thrustereffect.none" } )
You cannot retroactively change these definitions like that. Addons rely on the expected format to stay the same.

2024-09-04 13:19 UTC, robotboy655 requested changes

2024-11-07 14:28 UTC, friztailo commented on garrysmod/gamemodes/sandbox/entities/entities/base_gmodentity.lua
> +		if ( not self:BeingLookedAtByLocalPlayer() or self:GetNoDraw() ) then
In particular, you are right, but BeingLookedAtByLocalPlayer after caching will cost less than calling GetOverlayText

2024-11-07 17:48 UTC, neico commented
I've checked with the contributing file, and it's not stated there explicitly, but wasn't it generally agreed upon that things like operators shouldn't be changed from C-Style to lua style just for the sake of it?
I'm seeing quite a few `!` to `not` changes there.

2026-07-07 19:06 UTC, robotboy655 commented
This was partially merged in https://github.com/Facepunch/garrysmod/pull/2492 (with proper attribution)

Sorry I left this unchecked for so long, that's on me. Feel free to re-open a new PR with the remaining changes.

2026-07-07 19:06 UTC, closed without merging