Localization Support for key bindings.
Facepunch/garrysmod pull request #2126
Opened 2024-09-30 16:47 UTC by IBRS-4Ever

![image](https://github.com/user-attachments/assets/cae4d00f-9858-427b-9a26-e96a74ab5a55)
![image](https://github.com/user-attachments/assets/b6d6f819-5261-4a5f-897a-5a008fcb8f34)

2024-09-30 17:06 UTC, NovaDiablox commented
Nice! I always wondered if the missing lines were localizable. Thank you IBRS.

2024-10-01 18:34 UTC, robotboy655 requested changes
Usually newly added strings are appended to the end of the file, not at the top.

You will notice there are already GMod related strings there. You should also specify in the text file that the strings are for the keyboard settings specifically.

2024-10-02 03:01 UTC, IBRS-4Ever commented
You mean like this?
![image](https://github.com/user-attachments/assets/95fee1cf-66ae-4183-9081-0571e4b3b91d)

2024-10-02 15:07 UTC, robotboy655 approved these changes

2024-10-02 15:07 UTC, merged