Localization Support for Options - Legal
Facepunch/garrysmod pull request #2129
Opened 2024-10-03 08:44 UTC by IBRS-4Ever

![image](https://github.com/user-attachments/assets/372029e4-eaae-46e9-a04d-78c0a9aebc7e)

I couldn't find the file that defines the text 'Legal'.

Moved 
"GameUI_HTMLLoadingScreen" "Enable custom HTML loading screens"
"GameUI_CrosshairCustomize" "Crosshair Customization"
From garrysmod_english.txt to gameui_english.txt

![image](https://github.com/user-attachments/assets/afdfa2d4-ee16-40b4-a152-9abc04069d51)

2024-10-07 15:18 UTC, robotboy655 requested changes
I will change the `Legal` tab to use `#GameUI_Legal` or something similar after you fix the PR and it is merged.

2024-10-07 15:18 UTC, robotboy655 commented on garrysmod/resource/OptionsSubAudio.res
> +		"labelText"		"#GameUI_SoundEffectVolume"
You cannot not change existing localization strings.

`#GameUI_SoundEffectVolume` should remain where it was, and a new string can be added for `Sound effect volume` (for example `"#GameUI_SoundFXVolume"`)

2024-10-07 15:18 UTC, robotboy655 commented on garrysmod/resource/OptionsSubGModLegal.res
> +		"labelText"		"#GarrysMod_Legal_ChromiumEmbeddedFrameworkCredits"
the string could be shortened for `#GarrysMod_Legal_CEFCredits`

2024-10-08 09:10 UTC, IBRS-4Ever commented
Fixed:
![image](https://github.com/user-attachments/assets/571860be-8ef5-4cb7-81c8-9155052fb005)

2024-10-08 18:23 UTC, robotboy655 approved these changes

2024-10-08 18:24 UTC, merged