Adds Entity:AddSpawnFlags, Entity:RemoveSpawnFlags and Entity:SetSpawnFlags
Facepunch/garrysmod pull request #2138
Opened 2024-10-17 13:22 UTC by bloodycop7

Adds NPC:SetSpawnFlags, NPC:GiveSpawnFlag and NPC:RemoveSpawnFlag
In my opinion, it's easier to use than the bit. library, for those who don't understand it.

2024-10-17 20:22 UTC, Zaurzo commented
I feel like this should be an addition for all entities, not just npcs

2024-10-18 21:07 UTC, Zaurzo commented
There's already an extension file for entity (includes/extensions/entity.lua) so just add it there, no need for a new file. Also, extensions are included manually within `includes/init.lua`, so this npc.lua file is never going to be included unless you add it to init.lua

2024-10-22 12:23 UTC, Zaurzo approved these changes

2024-11-02 16:33 UTC, neico commented on garrysmod/lua/includes/extensions/player.lua
> +function meta:OnLadder()
```suggestion
function meta:IsOnLadder()
```
`On` prefixes should be reserved for Outputs, besides, we already have a few `IsOn` functions.
There's also to consider that NextBot can also use ladders, making it not bound specifically to the player.

If you want to pollute this PR with unrelated changes...

2024-11-02 23:21 UTC, robotboy655 commented
Please do not include unrelated changes to your Pull Requests.

If you want to suggest further additions, open a second/new Pull Request.

2024-11-03 11:30 UTC, neico commented
You could inline `newSpawnFlags` into the `SetKeyValue` call if you care about micro-optimization, as it's not used anywhere else and therefore saves a variable.

Also, I don't think an explicit check if flags already exist is needed, that way you can add multiple flags in a single call, or just one at a time, leaving it up to the individual.

If you want to complete the set though, add `SetSpawnFlags` and `ClearSpawnFlags`, the latter being a C++ function along those other 2.
Example:
```lua
function meta:SetSpawnFlags( Flags )
	return self:SetKeyValue( "spawnflags", Flags )
end

function meta:ClearSpawnFlags()
	return self:SetSpawnFlags( 0 )
end

function meta:AddSpawnFlags( Flags )
	return self:SetSpawnFlags( bit.bor( self:GetSpawnFlags(), Flags ) )
end

function meta:RemoveSpawnFlags( Flags )
	return self:SetSpawnFlags( bit.band( self:GetSpawnFlags(), bit.bnot( Flags ) ) )
end
```
Just a suggestion, and I'm not sure what robotboy655 thinks of such trivial functions.

2024-11-04 18:42 UTC, robotboy655 requested changes

2024-11-04 18:42 UTC, robotboy655 commented on garrysmod/lua/includes/extensions/entity.lua
> +end
This is not necessary, and there's no precedent for it in the codebase.

2024-11-04 18:42 UTC, robotboy655 commented on garrysmod/lua/includes/extensions/entity.lua
> +function meta:SetSpawnFlags( Flags )
Nitpick: the argument name is capitalized here, and not capitalized in your other changes. It should all be lowercase.

2024-11-05 06:57 UTC, neico commented
If you're going to nitpick then also mention that all instances of `flag` should be `flags`, including the function name, as you can add and remove multiple with each function.

2024-11-05 17:24 UTC, robotboy655 approved these changes

2024-11-13 17:35 UTC, robotboy655 commented
I don't think your recent changes are a good idea.

2024-11-26 13:00 UTC, Zaurzo commented
> > I don't think your recent changes are a good idea.
> 
> How come?

- It is inconsistent with the other Flag entity methods. None of them utilize varargs. 
- I'm pretty sure varargs are slower. I haven't confirmed that though, I'm not certain

2024-11-26 16:11 UTC, Zaurzo commented on garrysmod/lua/includes/extensions/entity.lua
> +    self:SetKeyValue( "spawnflags", bit.bor( flags ) )
Redundant use of `bit.bor` here

2024-11-27 09:45 UTC, neico commented on garrysmod/lua/includes/extensions/entity.lua
> +    self:SetKeyValue( "spawnflags", flags)
nitpick: the space after `flags`, or rather, the lack thereof

2024-11-27 11:40 UTC, Zaurzo approved these changes

2024-12-04 14:44 UTC, robotboy655 approved these changes

2024-12-04 14:44 UTC, merged