Make all post-processing conditional
Facepunch/garrysmod pull request #2173
Opened 2024-12-12 05:53 UTC by Denneisk

Optimizes post-processing by not having their hooks run when they're never used. Also removes some unnecessary checks or moves them to run only once.

Now post-processing hooks run only when needed.

I tested it and it all works fine, but I would appreciate anyone looking over this to make sure I didn't do any copying errors.

Was waiting for someone else to do this before I realized it'd be faster to do it myself.

2025-01-01 22:30 UTC, Cheatoid commented
I like the idea, but:
- Change this logic: `newValue != "0"` to check particular convar's boolean value instead (`ConVar:GetBool()`), this is because any non-zero value is considered true in engine, even `-1` and `123.45`. Consistency.
- Have you considered what would happen if any of those Lua files were (hot)reloaded (or loaded twice for whatever reason), no? Well, it would add another instance of those change callbacks into the list, and there be double shenanigans.

2025-01-02 04:24 UTC, Denneisk commented
Thanks for the response

> Change this logic: `newValue != "0"`

I thought all nonzero values were true for convars. I thought it would be simpler this way.

> (hot)reloaded

Thank you for considering this, that's a very important oversight.

> `render.SupportsPixelShaders_2_0()`

Good idea. Thanks.

2025-01-09 18:55 UTC, robotboy655 requested changes

2025-01-09 18:55 UTC, robotboy655 commented on garrysmod/lua/postprocess/bloom.lua
> +
Doing it this way introduces a regression where the result of `GAMEMODE:PostProcessPermitted` is not updated live.

I can understand `SupportsPixelShaders_2_0` being a static thing and can be moved outside of the hook.

I also think it's a better idea to make a the hook a local function and reference that in the `cvars.AddChangeCallback` callback, rather than nesting functions like this.

2025-01-09 18:55 UTC, robotboy655 commented on garrysmod/lua/postprocess/bloom.lua
> +} )
Unnecessary change.

2025-01-09 18:55 UTC, robotboy655 commented on garrysmod/lua/postprocess/dof.lua
> +	end)
Unnecessary change that does not conform to the style guidelines:
https://github.com/Facepunch/garrysmod/blob/master/CONTRIBUTING.md

2025-01-09 18:55 UTC, robotboy655 commented on garrysmod/lua/postprocess/frame_blend.lua
> +	if ( !GAMEMODE:PostProcessPermitted( "fb" ) ) then return end
Should be `"frame_blend"`, not `"fb"`

2025-01-09 18:55 UTC, robotboy655 commented on garrysmod/lua/postprocess/frame_blend.lua
> +	if ( !frame_blend.IsActive() ) then hook.Remove( "RenderFrameBlend", "RenderFrameBlend" ) return end
Why is this necessary?

2025-01-09 18:55 UTC, robotboy655 commented on garrysmod/lua/postprocess/super_dof.lua
> +	end )
This entire file is a mess. See previous comments. 

I also think this can be all done better, such as removing the hooks from `Panel.OnRemove` of the `SuperDOFWindow` for example.

2025-02-28 16:21 UTC, robotboy655 commented
I think 2 months is enough time to react to requested changes.

2025-02-28 16:21 UTC, closed without merging